Dockerfile: use rust:1.88.0-slim-trixie as base
MSRV for ort-2.0.0-rc.11 has been bumped to 1.88.
Linking of ONNX runtime 1.23.2 fails due to:
undefined reference to `__isoc23_strtol'
This is due to glibc on Debian Bookworm not including C23 symbols.
Use the Trixie variant of the Rust base container to fix that.